name: empedu
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  intl: ^0.19.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1 
  google_fonts: ^6.2.1

  # Loginsave
  shared_preferences: ^2.0.18

  # Youtube Conf
  youtube_player_flutter: ^9.1.1

  # Buku telp
  sqflite: ^2.0.0+3
  url_launcher: ^6.1.7
  path_provider: ^2.0.12

  # Calculator
  expressions: ^0.2.5+2
  cupertino_icons: ^1.0.8

  # Firebase confg
  firebase_messaging: ^15.2.0
  flutter_secure_storage: ^9.2.3
  firebase_auth: ^5.3.4
  fluttertoast: ^8.2.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  logger: ^2.5.0

  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icon_Apps.png"

flutter:
  uses-material-design: true

  

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/default_avatar.png
    - assets/ImageLogin.png
    - assets/Logo.png
    - assets/Icon_Apps.png
    - assets/Imyusi.JPG
    - assets/menggambar.png
    - assets/Menghitung.png
    - assets/Mewarnai.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
